use std::collections::HashMap;
use std::sync::Mutex;
use once_cell::sync::Lazy;

use crate::jets::*;


pub static JET_NAME_MAP: Lazy<Mutex<HashMap<Jet, &'static str>>> = Lazy::new(|| {
    let mut m = HashMap::new();
    // NOCKVM jets
    m.insert(jet_add as Jet, "jet_add");
    m.insert(jet_dec as Jet, "jet_dec");
    m.insert(jet_div as Jet, "jet_div");
    m.insert(jet_dvr as Jet, "jet_dvr");
    m.insert(jet_gte as Jet, "jet_gte");
    m.insert(jet_gth as Jet, "jet_gth");
    m.insert(jet_lte as Jet, "jet_lte");
    m.insert(jet_lth as Jet, "jet_lth");
    m.insert(jet_max as Jet, "jet_max");
    m.insert(jet_min as Jet, "jet_min");
    m.insert(jet_mod as Jet, "jet_mod");
    m.insert(jet_mul as Jet, "jet_mul");
    m.insert(jet_sub as Jet, "jet_sub");
    m.insert(jet_cap as Jet, "jet_cap");
    m.insert(jet_mas as Jet, "jet_mas");
    m.insert(jet_peg as Jet, "jet_peg");
    m.insert(jet_flop as Jet, "jet_flop");
    m.insert(jet_lent as Jet, "jet_lent");
    m.insert(jet_roll as Jet, "jet_roll");
    m.insert(jet_snag as Jet, "jet_snag");
    m.insert(jet_snip as Jet, "jet_snip");
    m.insert(jet_turn as Jet, "jet_turn");
    m.insert(jet_weld as Jet, "jet_weld");
    m.insert(jet_zing as Jet, "jet_zing");
    m.insert(jet_bex as Jet, "jet_bex");
    m.insert(jet_can as Jet, "jet_can");
    m.insert(jet_cat as Jet, "jet_cat");
    m.insert(jet_cut as Jet, "jet_cut");
    m.insert(jet_end as Jet, "jet_end");
    m.insert(jet_lsh as Jet, "jet_lsh");
    m.insert(jet_met as Jet, "jet_met");
    m.insert(jet_rap as Jet, "jet_rap");
    m.insert(jet_rep as Jet, "jet_rep");
    m.insert(jet_rev as Jet, "jet_rev");
    m.insert(jet_rip as Jet, "jet_rip");
    m.insert(jet_rsh as Jet, "jet_rsh");
    m.insert(jet_sew as Jet, "jet_sew");
    m.insert(jet_xeb as Jet, "jet_xeb");
    m.insert(jet_con as Jet, "jet_con");
    m.insert(jet_dis as Jet, "jet_dis");
    m.insert(jet_mix as Jet, "jet_mix");
    m.insert(jet_mug as Jet, "jet_mug");
    m.insert(jet_dor as Jet, "jet_dor");
    m.insert(jet_gor as Jet, "jet_gor");
    m.insert(jet_mor as Jet, "jet_mor");
    m.insert(jet_cue as Jet, "jet_cue");
    m.insert(jet_jam as Jet, "jet_jam");
    m.insert(jet_shas as Jet, "jet_shas");
    m.insert(jet_shax as Jet, "jet_shax");
    m.insert(jet_shay as Jet, "jet_shay");
    m.insert(jet_shal as Jet, "jet_shal");
    m.insert(jet_sha1 as Jet, "jet_sha1");
    m.insert(jet_trip as Jet, "jet_trip");
    m.insert(jet_last as Jet, "jet_last");
    m.insert(jet_bend as Jet, "jet_bend");
    m.insert(jet_comp as Jet, "jet_comp");
    m.insert(jet_glue as Jet, "jet_glue");
    m.insert(jet_pfix as Jet, "jet_pfix");
    m.insert(jet_plug as Jet, "jet_plug");
    m.insert(jet_pose as Jet, "jet_pose");
    m.insert(jet_sfix as Jet, "jet_sfix");
    m.insert(jet_cold as Jet, "jet_cold");
    m.insert(jet_cook as Jet, "jet_cook");
    m.insert(jet_easy as Jet, "jet_easy");
    m.insert(jet_here as Jet, "jet_here");
    m.insert(jet_just as Jet, "jet_just");
    m.insert(jet_mask as Jet, "jet_mask");
    m.insert(jet_shim as Jet, "jet_shim");
    m.insert(jet_stag as Jet, "jet_stag");
    m.insert(jet_stew as Jet, "jet_stew");
    m.insert(jet_stir as Jet, "jet_stir");
    m.insert(jet_scow as Jet, "jet_scow");
    m.insert(jet_mink as Jet, "jet_mink");
    m.insert(jet_mole as Jet, "jet_mole");
    m.insert(jet_mule as Jet, "jet_mule");
    m.insert(jet_ut_crop as Jet, "jet_ut_crop");
    m.insert(jet_ut_fish as Jet, "jet_ut_fish");
    m.insert(jet_ut_fuse as Jet, "jet_ut_fuse");
    m.insert(jet_ut_mint as Jet, "jet_ut_mint");
    m.insert(jet_ut_mull as Jet, "jet_ut_mull");
    m.insert(jet_ut_nest_dext as Jet, "jet_ut_nest_dext");
    m.insert(jet_ut_rest as Jet, "jet_ut_rest");
    m.insert(jet_puck as Jet, "jet_puck");
    m.insert(jet_shar as Jet, "jet_shar");
    m.insert(jet_sign as Jet, "jet_sign");
    m.insert(jet_veri as Jet, "jet_veri");
    m.insert(jet_siva_en as Jet, "jet_siva_en");
    m.insert(jet_siva_de as Jet, "jet_siva_de");
    m.insert(jet_sivb_en as Jet, "jet_sivb_en");
    m.insert(jet_sivb_de as Jet, "jet_sivb_de");
    m.insert(jet_sivc_en as Jet, "jet_sivc_en");
    m.insert(jet_sivc_de as Jet, "jet_sivc_de");
    // ZKVM jets are added in zkvm_jetpack::hot::produce_prover_hot_state
    Mutex::new(m)
});
